import 'gcode_line.dart';

/// User-facing text for every analyzer rule, in each app language.
///
/// Each entry is (what is wrong, how to fix it). `{name}` placeholders are
/// filled from [LineIssue.args]. G-code words stay in Latin script in every
/// language because that is how they appear on the control.
class GcodeRuleText {
  GcodeRuleText._();

  static ({String message, String fix}) of(LineIssue issue, String locale) {
    final t = (_tables[locale] ?? _en)[issue.rule] ?? _en[issue.rule];
    if (t == null) return (message: issue.rule, fix: '');
    return (message: _fill(t.$1, issue.args), fix: _fill(t.$2, issue.args));
  }

  /// Every rule id the parsers can report. Tests check all languages cover them.
  static Iterable<String> get rules => _en.keys;

  static Map<String, (String, String)>? table(String locale) => _tables[locale];

  static String _fill(String s, Map<String, String> args) =>
      s.replaceAllMapped(RegExp(r'\{(\w+)\}'), (m) => args[m.group(1)] ?? m.group(0)!);

  static const _tables = {'en': _en, 'fa': _fa, 'ro': _ro, 'ar': _ar};

  static const _en = <String, (String, String)>{
    'unknown_g': ('{code} is not a standard {dialect} G-code.',
        'Check it in the control manual: it may be a typo, a machine option, or a code from another control.'),
    'motion_conflict': ('{codes} on one line. A block can have only one motion mode.',
        'Put each move on its own line.'),
    'feed_zero': ('The feed rate is F0.',
        'Set a real feed rate. F0 stops the move or raises an alarm.'),
    'arc_no_center': ('{code} arc with no centre (I/J/K) or radius (R).',
        'Add I/J/K or R (CR= on Sinumerik). Without it the control alarms or cuts a different arc.'),
    'cycle_no_z': ('{code} canned cycle has no Z depth.',
        'Put the final depth Z on the first line of the cycle.'),
    'cycle_no_r': ('{code} canned cycle has no R plane.',
        'Add R, the plane the tool rapids to before it starts feeding. Some controls alarm without it; others reuse an old value.'),
    'cycle_no_q': ('{code} peck cycle has no peck depth Q.',
        'Add Q, the depth of each peck.'),
    'cycle_active': ('A canned cycle is still active here.',
        'Cancel it with G80 before the tool change or the end of the program.'),
    'm98_no_p': ('M98 has no P program number.',
        'Add the subprogram number, e.g. M98 P1000.'),
    'm6_no_tool': ('M06 tool change with no tool number (T).',
        'Add T on this line or before it, e.g. T1 M06.'),
    'spindle_off_cut': ('Cutting move with the spindle stopped.',
        'Start the spindle (S… M03 or M04) before this line. A tool change (M06) stops it.'),
    'no_feed': ('Cutting move before any feed rate (F) is set.',
        'Add F on this line or earlier.'),
    'no_units': ('Units (G20/G21) are not set before the first move.',
        'Put G20 (inch) or G21 (mm) in the safe-start line, so the program does not depend on the control\'s last state.'),
    'no_work_offset': ('No work offset (G54–G59) is selected before the first move.',
        'Select it in the safe-start line, e.g. G54. Otherwise the move uses whatever offset is active.'),
    'no_length_comp': ('Z move after the change to T{tool} without tool length compensation.',
        'Apply it with the first Z move, e.g. G43 H{tool} Z50.'),
    'h_mismatch': ('Length offset H{h} does not match tool T{t}.',
        'H is normally the tool number. Make sure H{h} is intended.'),
    'comp_on_arc': ('Cutter compensation {code} starts on an arc.',
        'Start G41/G42 on a G00/G01 line. Most controls alarm when compensation starts on G02/G03.'),
    'comp_no_d': ('{code} has no D offset number.',
        'Add the diameter offset, e.g. {code} D1.'),
    'comp_active': ('Cutter compensation is still on here.',
        'Cancel it with G40 before the tool change or the end of the program.'),
    'g28_absolute': ('G28 in absolute mode (G90) first moves to this point in work coordinates, then goes home.',
        'Use G91 G28 Z0. so the axis goes straight home without passing through the part.'),
    'no_decimal': ('{word} has no decimal point.',
        'Many Fanuc-type controls read this in thousandths (X10 = 0.010 mm). Write {fixed} if you mean whole units.'),
    'no_program_end': ('The program has no end ({codes}).',
        'End the program with {codes}.'),
    'sin_def_type': ('DEF without a data type.',
        'Declare the type, e.g. DEF REAL R_DEPTH.'),
    'sin_cycle_parens': ('{cycle} is called without its parameter list.',
        'Sinumerik cycles take their parameters in parentheses, e.g. {cycle}(…).'),
  };

  static const _fa = <String, (String, String)>{
    'unknown_g': ('{code} یک کد G استاندارد {dialect} نیست.',
        'آن را در دفترچهٔ کنترلر بررسی کنید: ممکن است اشتباه تایپی، آپشن ماشین یا کد کنترلر دیگری باشد.'),
    'motion_conflict': ('{codes} در یک خط. هر بلوک فقط یک حالت حرکت می‌تواند داشته باشد.',
        'هر حرکت را در یک خط جداگانه بنویسید.'),
    'feed_zero': ('مقدار پیشروی F0 است.',
        'یک پیشروی واقعی وارد کنید. F0 حرکت را متوقف می‌کند یا آلارم می‌دهد.'),
    'arc_no_center': ('کمان {code} بدون مرکز (I/J/K) یا شعاع (R).',
        'I/J/K یا R را اضافه کنید (در Sinumerik: CR=). بدون آن کنترلر آلارم می‌دهد یا کمان دیگری می‌تراشد.'),
    'cycle_no_z': ('سیکل ثابت {code} عمق Z ندارد.',
        'عمق نهایی Z را در خط اول سیکل بنویسید.'),
    'cycle_no_r': ('سیکل ثابت {code} صفحهٔ R ندارد.',
        'R را اضافه کنید؛ صفحه‌ای که ابزار قبل از شروع پیشروی سریع به آن می‌رود. بعضی کنترلرها بدون آن آلارم می‌دهند و بعضی مقدار قبلی را به کار می‌برند.'),
    'cycle_no_q': ('سیکل سوراخکاری مرحله‌ای {code} عمق هر مرحله (Q) ندارد.',
        'Q، یعنی عمق هر مرحله، را اضافه کنید.'),
    'cycle_active': ('یک سیکل ثابت اینجا هنوز فعال است.',
        'قبل از تعویض ابزار یا پایان برنامه آن را با G80 لغو کنید.'),
    'm98_no_p': ('M98 شمارهٔ برنامه (P) ندارد.',
        'شمارهٔ زیربرنامه را اضافه کنید، مثلاً M98 P1000.'),
    'm6_no_tool': ('تعویض ابزار M06 بدون شمارهٔ ابزار (T).',
        'T را در همین خط یا قبل از آن بنویسید، مثلاً T1 M06.'),
    'spindle_off_cut': ('حرکت برشی در حالی که اسپیندل خاموش است.',
        'قبل از این خط اسپیندل را روشن کنید (S… M03 یا M04). تعویض ابزار (M06) اسپیندل را خاموش می‌کند.'),
    'no_feed': ('حرکت برشی قبل از اینکه پیشروی (F) تعیین شود.',
        'F را در همین خط یا قبل از آن اضافه کنید.'),
    'no_units': ('واحد (G20/G21) قبل از اولین حرکت تعیین نشده است.',
        'G20 (اینچ) یا G21 (میلی‌متر) را در خط شروع ایمن بگذارید تا برنامه به آخرین وضعیت کنترلر وابسته نباشد.'),
    'no_work_offset': ('قبل از اولین حرکت، آفست قطعه (G54 تا G59) انتخاب نشده است.',
        'آن را در خط شروع ایمن انتخاب کنید، مثلاً G54. وگرنه حرکت با هر آفستی که فعال باشد انجام می‌شود.'),
    'no_length_comp': ('حرکت Z بعد از تعویض به ابزار T{tool} بدون جبران طول ابزار.',
        'آن را با اولین حرکت Z فعال کنید، مثلاً G43 H{tool} Z50.'),
    'h_mismatch': ('آفست طول H{h} با ابزار T{t} یکی نیست.',
        'معمولاً H همان شمارهٔ ابزار است. مطمئن شوید H{h} عمدی است.'),
    'comp_on_arc': ('جبران شعاع ابزار {code} روی کمان شروع شده است.',
        'G41/G42 را روی خط G00/G01 شروع کنید. بیشتر کنترلرها وقتی جبران روی G02/G03 شروع شود آلارم می‌دهند.'),
    'comp_no_d': ('{code} شمارهٔ آفست D ندارد.',
        'آفست قطر را اضافه کنید، مثلاً {code} D1.'),
    'comp_active': ('جبران شعاع ابزار اینجا هنوز فعال است.',
        'قبل از تعویض ابزار یا پایان برنامه آن را با G40 لغو کنید.'),
    'g28_absolute': ('G28 در حالت مطلق (G90) اول به این نقطه در مختصات قطعه می‌رود و بعد به خانه.',
        'از G91 G28 Z0. استفاده کنید تا محور مستقیم به خانه برود و از روی قطعه عبور نکند.'),
    'no_decimal': ('{word} ممیز اعشار ندارد.',
        'بسیاری از کنترلرهای نوع فانوک این را به هزارم می‌خوانند (X10 یعنی 0.010 میلی‌متر). اگر منظورتان واحد کامل است، {fixed} بنویسید.'),
    'no_program_end': ('برنامه پایان ({codes}) ندارد.',
        'برنامه را با {codes} تمام کنید.'),
    'sin_def_type': ('DEF بدون نوع داده.',
        'نوع را مشخص کنید، مثلاً DEF REAL R_DEPTH.'),
    'sin_cycle_parens': ('{cycle} بدون فهرست پارامترها فراخوانی شده است.',
        'سیکل‌های Sinumerik پارامترها را داخل پرانتز می‌گیرند، مثلاً {cycle}(…).'),
  };

  static const _ro = <String, (String, String)>{
    'unknown_g': ('{code} nu este un cod G standard {dialect}.',
        'Verifică-l în manualul controlerului: poate fi o greșeală de scriere, o opțiune a mașinii sau un cod al altui controler.'),
    'motion_conflict': ('{codes} pe aceeași linie. Un bloc poate avea un singur mod de mișcare.',
        'Pune fiecare mișcare pe o linie separată.'),
    'feed_zero': ('Avansul este F0.',
        'Setează un avans real. F0 oprește mișcarea sau dă alarmă.'),
    'arc_no_center': ('Arc {code} fără centru (I/J/K) sau rază (R).',
        'Adaugă I/J/K sau R (CR= pe Sinumerik). Fără ele controlerul dă alarmă sau taie alt arc.'),
    'cycle_no_z': ('Ciclul fix {code} nu are adâncimea Z.',
        'Scrie adâncimea finală Z pe prima linie a ciclului.'),
    'cycle_no_r': ('Ciclul fix {code} nu are planul R.',
        'Adaugă R, planul la care scula ajunge în rapid înainte de avans. Unele controlere dau alarmă fără el, altele folosesc o valoare veche.'),
    'cycle_no_q': ('Ciclul de găurire în trepte {code} nu are adâncimea pasului Q.',
        'Adaugă Q, adâncimea fiecărui pas.'),
    'cycle_active': ('Un ciclu fix este încă activ aici.',
        'Anulează-l cu G80 înainte de schimbarea sculei sau de sfârșitul programului.'),
    'm98_no_p': ('M98 nu are numărul de program P.',
        'Adaugă numărul subprogramului, de ex. M98 P1000.'),
    'm6_no_tool': ('Schimbare de sculă M06 fără număr de sculă (T).',
        'Adaugă T pe această linie sau înainte, de ex. T1 M06.'),
    'spindle_off_cut': ('Mișcare de așchiere cu arborele principal oprit.',
        'Pornește arborele (S… M03 sau M04) înainte de această linie. Schimbarea sculei (M06) îl oprește.'),
    'no_feed': ('Mișcare de așchiere înainte de setarea unui avans (F).',
        'Adaugă F pe această linie sau mai devreme.'),
    'no_units': ('Unitățile (G20/G21) nu sunt setate înainte de prima mișcare.',
        'Pune G20 (inch) sau G21 (mm) în linia de start sigur, ca programul să nu depindă de ultima stare a controlerului.'),
    'no_work_offset': ('Niciun decalaj de lucru (G54–G59) nu este selectat înainte de prima mișcare.',
        'Selectează-l în linia de start sigur, de ex. G54. Altfel mișcarea folosește decalajul activ în acel moment.'),
    'no_length_comp': ('Mișcare în Z după schimbarea pe T{tool} fără compensarea lungimii sculei.',
        'Aplic-o la prima mișcare în Z, de ex. G43 H{tool} Z50.'),
    'h_mismatch': ('Corecția de lungime H{h} nu corespunde sculei T{t}.',
        'De obicei H este numărul sculei. Verifică dacă H{h} este intenționat.'),
    'comp_on_arc': ('Compensarea razei {code} începe pe un arc.',
        'Pornește G41/G42 pe o linie G00/G01. Majoritatea controlerelor dau alarmă când compensarea începe pe G02/G03.'),
    'comp_no_d': ('{code} nu are numărul de corecție D.',
        'Adaugă corecția de diametru, de ex. {code} D1.'),
    'comp_active': ('Compensarea razei sculei este încă activă aici.',
        'Anulează-o cu G40 înainte de schimbarea sculei sau de sfârșitul programului.'),
    'g28_absolute': ('G28 în mod absolut (G90) merge întâi în acest punct în coordonatele piesei, apoi în origine.',
        'Folosește G91 G28 Z0. ca axa să meargă direct în origine fără să treacă prin piesă.'),
    'no_decimal': ('{word} nu are punct zecimal.',
        'Multe controlere de tip Fanuc citesc asta în miimi (X10 = 0,010 mm). Scrie {fixed} dacă te referi la unități întregi.'),
    'no_program_end': ('Programul nu are sfârșit ({codes}).',
        'Încheie programul cu {codes}.'),
    'sin_def_type': ('DEF fără tip de date.',
        'Declară tipul, de ex. DEF REAL R_DEPTH.'),
    'sin_cycle_parens': ('{cycle} este apelat fără lista de parametri.',
        'Ciclurile Sinumerik primesc parametrii în paranteze, de ex. {cycle}(…).'),
  };

  static const _ar = <String, (String, String)>{
    'unknown_g': ('{code} ليس كود G قياسياً في {dialect}.',
        'تحقق منه في دليل وحدة التحكم: قد يكون خطأً مطبعياً أو خياراً في الماكينة أو كوداً لوحدة تحكم أخرى.'),
    'motion_conflict': ('{codes} في سطر واحد. يمكن أن يحتوي البلوك على نمط حركة واحد فقط.',
        'ضع كل حركة في سطر منفصل.'),
    'feed_zero': ('معدل التغذية F0.',
        'حدد تغذية حقيقية. F0 يوقف الحركة أو يسبب إنذاراً.'),
    'arc_no_center': ('قوس {code} بدون مركز (I/J/K) أو نصف قطر (R).',
        'أضف I/J/K أو R (في Sinumerik: CR=). بدونها تعطي وحدة التحكم إنذاراً أو تقطع قوساً مختلفاً.'),
    'cycle_no_z': ('الدورة الثابتة {code} بدون عمق Z.',
        'اكتب العمق النهائي Z في السطر الأول من الدورة.'),
    'cycle_no_r': ('الدورة الثابتة {code} بدون مستوى R.',
        'أضف R، وهو المستوى الذي تنتقل إليه الأداة بسرعة قبل بدء التغذية. بعض وحدات التحكم تعطي إنذاراً بدونه وبعضها يستخدم قيمة قديمة.'),
    'cycle_no_q': ('دورة الثقب المتقطع {code} بدون عمق النقرة Q.',
        'أضف Q، وهو عمق كل نقرة.'),
    'cycle_active': ('لا تزال دورة ثابتة نشطة هنا.',
        'ألغها بـ G80 قبل تغيير الأداة أو نهاية البرنامج.'),
    'm98_no_p': ('M98 بدون رقم البرنامج P.',
        'أضف رقم البرنامج الفرعي، مثل M98 P1000.'),
    'm6_no_tool': ('تغيير الأداة M06 بدون رقم أداة (T).',
        'أضف T في هذا السطر أو قبله، مثل T1 M06.'),
    'spindle_off_cut': ('حركة قطع والمغزل متوقف.',
        'شغّل المغزل (S… M03 أو M04) قبل هذا السطر. تغيير الأداة (M06) يوقفه.'),
    'no_feed': ('حركة قطع قبل تحديد أي معدل تغذية (F).',
        'أضف F في هذا السطر أو قبله.'),
    'no_units': ('لم تُحدَّد الوحدات (G20/G21) قبل أول حركة.',
        'ضع G20 (بوصة) أو G21 (مم) في سطر البداية الآمنة حتى لا يعتمد البرنامج على آخر حالة لوحدة التحكم.'),
    'no_work_offset': ('لم يتم اختيار إزاحة العمل (G54–G59) قبل أول حركة.',
        'اخترها في سطر البداية الآمنة، مثل G54. وإلا ستستخدم الحركة أي إزاحة نشطة.'),
    'no_length_comp': ('حركة Z بعد تغيير الأداة إلى T{tool} بدون تعويض طول الأداة.',
        'فعّله مع أول حركة Z، مثل G43 H{tool} Z50.'),
    'h_mismatch': ('إزاحة الطول H{h} لا تطابق الأداة T{t}.',
        'عادةً يكون H هو رقم الأداة. تأكد أن H{h} مقصود.'),
    'comp_on_arc': ('تعويض نصف قطر الأداة {code} يبدأ على قوس.',
        'ابدأ G41/G42 على سطر G00/G01. معظم وحدات التحكم تعطي إنذاراً عند بدء التعويض على G02/G03.'),
    'comp_no_d': ('{code} بدون رقم إزاحة D.',
        'أضف إزاحة القطر، مثل {code} D1.'),
    'comp_active': ('لا يزال تعويض نصف قطر الأداة نشطاً هنا.',
        'ألغه بـ G40 قبل تغيير الأداة أو نهاية البرنامج.'),
    'g28_absolute': ('G28 في الوضع المطلق (G90) ينتقل أولاً إلى هذه النقطة في إحداثيات القطعة ثم إلى نقطة الصفر.',
        'استخدم G91 G28 Z0. حتى يعود المحور مباشرة دون المرور عبر القطعة.'),
    'no_decimal': ('{word} بدون فاصلة عشرية.',
        'كثير من وحدات التحكم من نوع فانوك تقرأ هذا بالأجزاء من الألف (X10 تعني 0.010 مم). اكتب {fixed} إذا كنت تقصد وحدات كاملة.'),
    'no_program_end': ('البرنامج بدون نهاية ({codes}).',
        'أنهِ البرنامج بـ {codes}.'),
    'sin_def_type': ('DEF بدون نوع بيانات.',
        'حدد النوع، مثل DEF REAL R_DEPTH.'),
    'sin_cycle_parens': ('تم استدعاء {cycle} بدون قائمة المعاملات.',
        'دورات Sinumerik تأخذ معاملاتها بين قوسين، مثل {cycle}(…).'),
  };
}
